version: 0.2

env:
  variables:
    ECR_REPO_NAME: springboot-app
    CONTAINER_NAME: springboot-container

phases:
  pre_build:
    commands:
      - echo Logging in to ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Building Spring Boot app...
      - ./mvnw package -DskipTests
      - echo Building Docker image...
      - docker build -t springboot-app .
      - docker tag springboot-app:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/springboot-app:latest
  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/springboot-app:latest
      - echo Writing image definitions file...
      - printf '[{"name":"springboot-container","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/springboot-app:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
